spring:
  application:
    name: product
  data:
    mongodb:
      database: products
      username: root
      password: root
      authentication-database: admin
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5